spring:
    application:
        name: Athena
    datasource:
        url: jdbc:h2:file:./database
        driverClassName: org.h2.Driver
        username: sa
        password: password
    h2:
        console:
            enabled: true
    jpa:
        defer-datasource-initialization: true
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect
    sql:
        init:
            mode: always
        data-locations: classpath:data.sql
